"""Configuration loading for experiments.

Tunables live in a YAML file rather than in code, so a reported number can be
regenerated by rerunning the file that produced it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from dit.evaluation.experiment import ExperimentConfig

EXPERIMENT_KEYS = set(ExperimentConfig.__dataclass_fields__)


def load_config(path: str | Path) -> dict[str, object]:
    """Load a YAML experiment file and validate experiment keys."""

    try:
        import yaml
    except ImportError as exc:
        raise RuntimeError("PyYAML is required to read config files") from exc

    source = Path(path)
    if not source.exists():
        raise FileNotFoundError(f"config file not found: {source}")
    payload = yaml.safe_load(source.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"config root must be a mapping, got {type(payload).__name__}")
    # Only ``experiment`` is authoritative; ``description`` is a human note.
    # Anything else fails loudly rather than being silently ignored.
    allowed_top_level = {"experiment", "description"}
    unknown_top_level = set(payload) - allowed_top_level
    if unknown_top_level:
        raise ValueError(
            f"unknown top-level config keys {sorted(unknown_top_level)}; "
            f"only {sorted(allowed_top_level)} are recognised. Dataset selection "
            "and output paths are command-line flags, not config keys."
        )
    experiment = dict(payload.get("experiment", {}) or {})
    unknown = set(experiment) - EXPERIMENT_KEYS
    if unknown:
        raise ValueError(
            f"unknown experiment keys {sorted(unknown)}; expected a subset of "
            f"{sorted(EXPERIMENT_KEYS)}"
        )
    payload["experiment"] = experiment
    return payload


def config_to_experiment(payload: dict[str, object]) -> ExperimentConfig:
    """Build an :class:`ExperimentConfig` from a loaded payload."""

    experiment = payload.get("experiment", {}) or {}
    return ExperimentConfig(**{key: value for key, value in experiment.items()})


def experiment_payload(config: ExperimentConfig) -> dict[str, object]:
    """Inverse of :func:`config_to_experiment`, for reporting."""

    return config.describe()
